# Generated by Django 2.0.3 on 2018-03-12 10:21


from django.db import migrations
import django.db.models.deletion



def load_countries(apps, schema_editor):
    Countries = apps.get_model("app", "Countries")
    countries_obj = Countries(id=1, country='UK')
    countries_obj.save()

    countries_obj = Countries(id=2, country='England')
    countries_obj.save()
    
    countries_obj = Countries(id=3, country='Wales')
    countries_obj.save()

    countries_obj = Countries(id=4, country='Scotland')
    countries_obj.save()

def delete_countries(apps, schema_editor):
    Countries = apps.get_model("app", "Countries")
    Countries.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
    migrations.RunPython(load_countries,delete_countries),
    ]

